<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI2S0NYX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI2S0NYX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI2S0NYX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI2S0NYX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI2S0NYX\App_KernelDevDebugContainer([
    'container.build_hash' => 'I2S0NYX',
    'container.build_id' => '63ae7390',
    'container.build_time' => 1738061656,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI2S0NYX');
