<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMCYEV1q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMCYEV1q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMCYEV1q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMCYEV1q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMCYEV1q\App_KernelDevDebugContainer([
    'container.build_hash' => 'MCYEV1q',
    'container.build_id' => '57647dd6',
    'container.build_time' => 1738070192,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMCYEV1q');
