<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM4JNgru\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM4JNgru/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM4JNgru.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM4JNgru\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM4JNgru\App_KernelDevDebugContainer([
    'container.build_hash' => 'M4JNgru',
    'container.build_id' => '0fcbe0f2',
    'container.build_time' => 1738075886,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM4JNgru');
