name: Symfony Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo, pdo_sqlite

    - name: Set up DATABASE_URL
      run: echo "DATABASE_URL=sqlite:///%kernel.project_dir%/data/database.sqlite" >> $GITHUB_ENV

    - name: Copy .env.test.local (if exists)
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

    - name: Remove .env.test.local (force SQLite)
      run: rm -f .env.test.local

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist 

    - name: Create Database
      run: |
        mkdir -p data
        touch data/database.sqlite
        ls -l data/  # Debug

    - name: Run Migrations
      run: php bin/console doctrine:schema:update

    - name: Clear Doctrine Cache
      run: php bin/console doctrine:cache:clear-metadata

    - name: Debug Database Schema
      run: php bin/console doctrine:schema:validate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
